title: <p align="center"> Jaya Singh </p>
logo: /assets/img/Jaya_Singh.jpeg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jaya-singh-8092303a/">LinkedIn</a> |
  <a href="https://github.com/jayasingh0742-coder">GitHub</a>
  
  <br>   
  I'm a technical architect working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Involved in Solving problems with Business Intelligence and Machine Learning within Fintech Domain
  <br>
  </p>



theme: jekyll-theme-minimal
